"""Added wishlist content hash

Revision ID: 117e2c151e89
Revises: 8a7f140ca4fd
Create Date: 2020-10-15 18:06:54.538610

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "117e2c151e89"
down_revision = "8a7f140ca4fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wishlist", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "content_hash",
                sa.Integer(),
                nullable=False,
                server_default=str(hash("")),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wishlist", schema=None) as batch_op:
        batch_op.drop_column("content_hash")

    # ### end Alembic commands ###
