"""empty message

Revision ID: 4e725030abd5
Revises: 
Create Date: 2020-10-11 14:09:41.987084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e725030abd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stars', sa.Float(), nullable=False),
    sa.Column('link', sa.String(length=128), nullable=True),
    sa.Column('link_image', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishlist_timestamp'), 'wishlist', ['timestamp'], unique=False)
    op.create_table('wishlist_product',
    sa.Column('whishlist_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['whishlist_id'], ['wishlist.id'], ),
    sa.PrimaryKeyConstraint('whishlist_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist_product')
    op.drop_index(op.f('ix_wishlist_timestamp'), table_name='wishlist')
    op.drop_table('wishlist')
    op.drop_table('product')
    # ### end Alembic commands ###
