"""Change sub ts to expires

Revision ID: 803d47a0fc35
Revises: 8e3680d27a9c
Create Date: 2020-10-19 15:19:46.106627

"""
import time

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "803d47a0fc35"
down_revision = "8e3680d27a9c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscription", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "expires",
                sa.Integer(),
                server_default=str(int(time.time() + 24 * 3600)),
                nullable=False,
            )
        )
        batch_op.drop_column("timestamp")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("subscription", schema=None) as batch_op:
        batch_op.add_column(sa.Column("timestamp", sa.INTEGER(), nullable=False))
        batch_op.drop_column("expires")

    # ### end Alembic commands ###
