"""Fixed false relationship name for product source

Revision ID: 82a2875cf627
Revises: 67c396550a32
Create Date: 2020-10-13 19:57:29.685564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a2875cf627'
down_revision = '67c396550a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('source_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
