"""Added item quantity/id

Revision ID: 8a7f140ca4fd
Revises: 3dcec3630aa3
Create Date: 2020-10-14 15:15:32.178361

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8a7f140ca4fd"
down_revision = "3dcec3630aa3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.add_column(sa.Column("item_id", sa.String(length=64), nullable=True))
        batch_op.add_column(
            sa.Column("quantity", sa.Integer(), server_default="1", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.drop_column("quantity")
        batch_op.drop_column("item_id")

    # ### end Alembic commands ###
