"""More More rel fixes

Revision ID: ddaa084eed8b
Revises: 82a2875cf627
Create Date: 2020-10-13 20:07:06.128061

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ddaa084eed8b"
down_revision = "67c396550a32"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "foreign_key_contraint", "source", ["source_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.drop_constraint("foreign_key_contraint", type_="foreignkey")
        batch_op.drop_column("source_id")

    # ### end Alembic commands ###
